# Generated by Django 4.1.7 on 2023-02-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainImages',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='')),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
