# Generated by Django 4.1.7 on 2023-02-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='added_date',
        ),
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('test_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
