# Generated by Django 4.1.7 on 2023-02-25 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_person_added_date_testimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='testimage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.person'),
        ),
    ]
