# Generated by Django 4.1.7 on 2023-04-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_testimage_image_alter_testimage_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimage',
            name='matrix_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='trainimage',
            name='matrix_data',
            field=models.TextField(default='[]'),
        ),
    ]
